version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./alko-similar-db:/var/lib/postgresql/data
      - ./alko-similar-server/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  server:
    image: essijukkala/alko-similar:server
    container_name: server
    links:
      - db
  client:
    image: essijukkala/alko-similar:client
    container_name: client
    links: 
      - server
  nginx:
    image: nginx:latest
    container_name: nginx
    links: 
      - client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw