version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: alko-similar-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./alko-similar-db:/var/lib/postgresql/data
      - ./alko-similar-server/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  server:
    image: alko-similar-server-dev
    container_name: alko-similar-server-dev
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/postgres?user=postgres&password=postgres
    links:
      - db
    build:
      context: ./alko-similar-server
      dockerfile: dev.Dockerfile
    volumes:
      - ./alko-similar-server:/app
    ports:
      - 3000:3000
      - 40000:40000 # repl
  client:
    image: alko-similar-client-dev
    container_name: alko-similar-client-dev
    links:
      - server
    build:
      context: ./alko-similar-client
      dockerfile: dev.Dockerfile
    volumes:
      - ./alko-similar-client:/app
    ports:
      - 3001:3001
      - 9630:9630 # for live reload
      - 3333:3333 # nrepl