(ns alko-similar-client.views.colors)

(def color-variants
  {:lager "bg-lager text-white"
   :tumma_lager "bg-tumma_lager text-white"
   :pils "bg-pils text-black"
   :vahva_lager "bg-vahva_lager text-white"
   :vehnäolut "bg-vehnäolut text-black"
   :ale "bg-ale text-white"
   :stout_&_porter "bg-stout_&_porter text-white"
   :erikoisuus "bg-erikoisuus text-white"
   :ipa "bg-ipa text-white"
   :marjaisa_&_raikas "bg-marjaisa_&_raikas text-white"
   :pehmeä_&_hedelmäinen "bg-pehmeä_&_hedelmäinen text-black"
   :mehevä_&_hilloinen "bg-mehevä_&_hilloinen text-white"
   :vivahteikas_&_kehittynyt "bg-vivahteikas_&_kehittynyt text-white"
   :roteva_&_voimakas "bg-roteva_&_voimakas text-white"
   :pehmeä_&_kepeä "bg-pehmeä_&_kepeä text-black"
   :lempeä_&_makeahko "bg-lempeä_&_makeahko text-white"
   :pirteä_&_hedelmäinen "bg-pirteä_&_hedelmäinen text-white"
   :vivahteikas_&_ryhdikäs "bg-vivahteikas_&_ryhdikäs text-white"
   :runsas_&_paahteinen "bg-runsas_&_paahteinen text-white"
   :kepeä_&_viljainen_viskit "bg-kepeä_&_viljainen_viskit text-black"
   :pehmeä_&_hedelmäinen_viskit "bg-pehmeä_&_hedelmäinen_viskit text-white"
   :hedelmäinen_&_aromikas_viskit "bg-hedelmäinen_&_aromikas_viskit text-white"
   :vivahteikas_&_ryhdikäs_viskit "bg-vivahteikas_&_ryhdikäs_viskit text-white"
   :runsas_&_voimakas_viskit "bg-runsas_&_voimakas_viskit text-white"
   :greippinen "bg-greippinen text-black"
   :sitruksinen "bg-sitruksinen text-black"
   :hedelmäinen "bg-hedelmäinen text-white"
   :marjaisa "bg-marjaisa text-white"
   :maustetut_ja_muut "bg-maustetut_ja_muut text-white"
   :vs-konjakit "bg-vs-konjakit text-black"
   :vsop-konjakit "bg-vsop-konjakit text-white"
   :xo-konjakit "bg-xo-konjakit text-white"
   :muut_konjakit "bg-muut_konjakit text-white"
   :tastestyle_441 "bg-tastestyle_441"
   :tastestyle_443 "bg-tastestyle_443"
   :tastestyle_445 "bg-tastestyle_445"
   :tastestyle_447 "bg-tastestyle_447"
   :tastestyle_449 "bg-tastestyle_449"})