name: Cert renewal check

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
    - name: Health Check
      uses: jtalk/url-health-check-action@v3
      with:
        # Check the following URLs one by one sequentially
        url: https://${{ secrets.INSTANCE_IP }}/api/health
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 10s # Optional, only applicable to max-attempts > 1
  renew-check:
    runs-on: ubuntu-latest
    needs: health-check
    steps:
      - name: 'Run cert renewal check'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          script: |
            docker compose run --rm certbot renew