name: Cert renewal check

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  renew-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run cert renewal check'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          script: |
            docker compose run --rm certbot renew
