name: Clojure Client CI

defaults:
  run:
    working-directory: alko-similar-client

on:
  push:
    branches:
      - main
    paths:
      - alko-similar-client/**
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - alko-similar-client/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          clj-kondo: 'latest'             # Clj-kondo

    - name: Run linter
      run: clj-kondo --lint src

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: lint
    # Only run on main branch, not on pull requests
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:alko-similar-client"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: essijukkala/alko-similar:client
  deploy:
    name: Deploy docker image
    runs-on: ubuntu-latest
    needs: build
    # Only run on main branch, not on pull requests
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Update docker-compose.yml'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~"
      - name: 'Update nginx.conf'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          source: "nginx-conf/nginx.conf"
          target: "~/nginx-conf"
      - name: 'Stop old server, pull new image, start again'
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_DB }}
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB
          script: |
            export POSTGRES_USER=$POSTGRES_USER
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            export POSTGRES_DB=$POSTGRES_DB
            docker compose down
            docker compose pull
            docker compose up -d
  health-check:
    runs-on: ubuntu-latest
    name: Health check
    needs: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Health Check
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: jtalk/url-health-check-action@v3
      with:
        # Check the following URLs one by one sequentially
        url: https://${{ secrets.INSTANCE_IP }}/api/health
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 10s # Optional, only applicable to max-attempts > 1
