name: Clojure Server CI

defaults:
  run:
    working-directory: alko-similar-server

on:
  push:
    branches:
      - main
    paths:
      - alko-similar-server/**
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - alko-similar-server/**

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Setup Clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          lein: 'latest'                  # Leiningen
          clj-kondo: 'latest'             # Clj-kondo

    - name: Run linter
      run: clj-kondo --lint src

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

  deploy:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: lint-and-test
    # Only run on main branch, not on pull requests
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:alko-similar-server"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: essijukkala/alko-similar:server